[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # Specifica il bundler per le funzioni Node.js

# Opzionale: Se vuoi rendere l'URL della funzione più pulito,
# ad esempio chiamando /api/cercaVoliSerpApi invece di /.netlify/functions/cercaVoliSerpApi
# [[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/:splat"
#  status = 200
